### PR TITLE
Release v0.26.0

### PR DESCRIPTION
**Pull request by jasonpaulos**
Update changelog and `setup.py` to prepare for version 0.26.0 release.

### CODE REVIEW

**Review by jannotti — APPROVED** [review]
Weren't there two extra fields that got added because we forgot them from v9?

**Comment by jasonpaulos** [comment]
@jannotti let me know if I have this right: v9 didn't introduce any new fields, but v10 introduced `global AssetCreateMinBalance` and `global AssetOptInMinBalance`, which were developed some time ago (and of course the more recent `global GenesisHash`

**Comment by jannotti** [comment]
Sorry, it was v6.  These were in your v10 PR, so I figured they should be mentioned here.

:any:`Global.opcode_budget()`               :code:`TealType.uint64` 6                    The remaining cost that can be spent by opcodes in this program
:any:`Global.caller_app_id()`               :code:`TealType.uint64` 6                    The ID of the application that called the current application, or zero. Application mode only
:any:`Global.caller_app_address()`          :code:`TealType.bytes`  6                    32 byte address of the application that called the current application, or the zero address. Application mode only.

**Comment by jasonpaulos** [comment]
Oh those were just missing from the docs. They've still been functional

**Pull request merged**
