### PR TITLE
PyTeal logo added

### PR DESCRIPTION
**Pull request by ipaleka**
Hi guys!

I'm writing a tutorial for the Dev portal and as there should be some kind of hero image I noticed there's no logo for PyTeal. This is the version I'll use in the tutorial.

### CODE REVIEW

**Comment by ipaleka** [comment]
This is how it looks like in README: https://github.com/ipaleka/pyteal

**Comment by jasonpaulos** [comment]
Hi @ipaleka, thank you for creating this! Would it be possible to create a version with a capital P and T so we can see how that looks?

**Comment by ipaleka** [comment]
Yes, I may do that, but this version emphasized the A on purpose. :)

**Comment by ipaleka** [comment]
pyteal

[Preview in README](https://github.com/ipaleka/pyteal)

**Review by jasonpaulos — APPROVED** [review]
This looks great! Thank you for modifying the image to have capital letters. I also liked the previous version but it's best if the capitalization of the logo is consistent with how our docs reference PyTeal.

Thank you again for adding this!

**Comment by ipaleka** [comment]
pyteal

https://raw.githubusercontent.com/ipaleka/pyteal/master/docs/pyteal.svg

https://github.com/ipaleka/pyteal

**Pull request merged**
