### PR TITLE
Prep CHANGELOG for v0.11.0

### PR DESCRIPTION
**Pull request by michaeldiamant**
Provides `CHANGELOG.md` updates for v0.11.0.

### CODE REVIEW

**Comment by ahangsu** [comment]
minor: keep track of #268 just merged?

**Review by tzaffi — COMMENTED** [review]
As @ahangsu pointed out, I recommend a one liner to the effect
* Remove outdated Jupyter notebook demo #268

**Review by tzaffi — APPROVED** [review]
LGTM

**Review by ahangsu — APPROVED** [review]

**Review by jasonpaulos — APPROVED** [review]

**Comment by ahangsu** [comment]
Reminder, add: Fix docs warning about multiple OptimizeOptions targets (PR #271)

**Pull request merged**
