### PR TITLE
Add ScratchVar

### LINKED ISSUE #32: Allow programs to use scratch space
Hey PyTEAL maintainers,
first of all thank you for this amazing library. 

Can ask to add `ScratchSlot` examples to the documentation? Or at least here as a comment so I will be able to prepare a PR with documentation update. Thank you!

### PR DESCRIPTION
**Pull request by krotkiewicz**
Add `ScratchVar`, an interface for programs to store and load values from scratch space.

Example:
```python
myvar = ScratchVar(TealType.uint64)
program = Seq([
     myvar.store(Int(5)),
     Assert(myvar.load() == Int(5))
])
```

Fixes #32

### CODE REVIEW

**Comment by krotkiewicz** [comment]
Hey @jasonpaulos let me know if you like it. I will add documentation after getting your 👍

**Comment by jasonpaulos** [comment]
Hi @krotkiewicz, thanks for the PR! I've made some changes to the implementation and tests but I've kept the basic idea. If you'd like to add some docs too, feel free to add a new page to the documentation by making a new RST file in the docs folder and link to it from `index.rst`.

**Comment by krotkiewicz** [comment]
@jasonpaulos done, feel free to edit or reword it before merging. Thanks.

**Comment by jasonpaulos** [comment]
Thanks @krotkiewicz, this will make it into the next version!

**Pull request merged**
