### PR TITLE
Proposal to refactor examples name and exclude tests from being shipped.

### PR DESCRIPTION
**Pull request by CiottiGiorgio**

### CODE REVIEW

**Review by jasonpaulos — COMMENTED** [review]
Thanks for the explanation in #608 and for creating this PR to remedy the situation.

I wasn't aware that the examples folder was being installed as a standalone package -- I think this behavior is not intentional nor desired.

So instead of renaming, could we keep the folder as `examples`, but change `setup.py` to only include the `pyteal` package?

**Comment by ahangsu** [comment]
^ Up Jason's point, I think it would be nice to not involve too much change in package structure itself, but rather specifying the only package data is from `pyteal` directory, by specifying in `setup.py`.

**Comment by CiottiGiorgio** [comment]
Sounds good. I'll modify this PR

**Review by ahangsu — APPROVED** [review]
lgtm

**Comment by CiottiGiorgio** [comment]
I can't merge this as I don't have write privileges

**Review by jasonpaulos — APPROVED** [review]

**Pull request merged**
