### PR TITLE
Implement TEAL 4 basic ops

### PR DESCRIPTION
**Pull request by jasonpaulos**
This PR adds support for the following feature from TEAL v4:
* `extra_program_pages` transaction field
* `GeneratedID` expression
* `BitLen` expression
* `Sqrt` expression
* `ShiftLeft`, `ShiftRight`, and `Exp` expressions
  *  Also overloads the Python operators for these operations

### CODE REVIEW

**Comment by jasonpaulos** [comment]
@jdtzmn does `GeneratedID(txnIndex)` make sense for the `gaid(s)` opcode?

**Comment by jdtzmn** [comment]
Yes, I think that makes sense. @jannotti any thoughts?

**Comment by jannotti** [comment]
I'm ambivalent - I don't like that it implies the g is for "generated", as we're going for "group", as with gload and gtxn. But I guess you won't need the g's because it is known from context in pyteal? How will gload appear? Does the g in gtxn show up in pyteal naming?

I do like 'generated' compared to 'created' for being when clearer that it's about the ID that was made in that transaction.

So... I think it's good if you feel it fits in well with other choices in pyteal. I don't know it all that well.

**Review by jdtzmn — APPROVED** [review]
Looks good! I like the overloads.

**Comment by jasonpaulos** [comment]
@jannotti `gload` will appear in a separate PR after some design work -- I want to explore the idea of having `Export`/`Import` operations that would allow contracts to share values using `gload`.

And yes g does show up in the `Gtxn` variable, but that's currently the only place. I think I'll merge this with `GeneratedID`, but if we change our mind about that name we'll have some time to update it before PyTeal gets released.

**Comment by jasonpaulos** [comment]
Closes #65.

**Pull request merged**
